### ISSUE TITLE
Acceptance tests fail

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#800] opened 2023-10-24 19:27 UTC
Acceptance tests currently fail on ` can walk through an nih submission workflow and make a submission - base case`.

**Comment by markpatton** [comment] 2023-10-24 19:52
Fails in a different place on another run.

**Comment by jabrah** [comment] 2023-10-25 11:38
Looks to me like it's caused by this UI change, which hasn't been accounted for in the acceptance tests yet: https://github.com/eclipse-pass/main/issues/402

**Comment by jabrah** [comment] 2023-10-25 12:28
PR merged, rerunning tests in CI to confirm

**Closed** 2023-10-25 12:34 UTC
Labels: UI
