### ISSUE TITLE
Investigate the Hosting of Local Schemas for the Pass Metadata-Schema Service

### ISSUE THREAD

**Issue by tsande16** [eclipse-pass/main#496] opened 2023-03-22 18:30 UTC
Currently the schemas are stored locally or on github. It may simplify the management of the schemas to have them stored in the database. They could be stored as JSON objects in the postgresql database. They could be stored as plain text as well. This may require the refactoring of the data model, but it would be a minimal impact.

**Comment by jabrah** [comment] 2023-04-18 15:06
The current behavior of the schema resolution does seem a bit odd, now that I've had a chance to start integrating the schema service with the demo stack. It seems like `repository.schemas` property (contains a list of URLs) is used to find schemas, which is fine. The schema URLs, however, are absolute URLs, but faked. Their current purpose is only to have the right path that points to a local schema baked into the Spring Boot app (in `schemaservice/src/resources`). I believe this is holdover behavior from the initial porting work, moving the Go code to Java in the old Fedora-based infra.

My understanding was that the original intended behavior would read the URL path to see if there was a local (baked-in) copy, but if one was not found, would resolve the URL to download the schema and hold it in local cache. I don't think that latter part happens in the current schema service impl.

Ultimately, maybe it doesn't matter too much if we use real/resolvable URLs here, or if we use URLs at all to point to schemas if we are only resolving files held within the application.

Moving schemas into the DB may be nice to simplify this part of the schema service in order to leverage Elide's data resolution, caching, etc

**Comment by dkriethof** [comment] 2023-07-20 15:38
this has been resolved by schema services support

**Closed by dkriethof** 2023-07-20 15:38 UTC
Labels: Analysis & Design
