### ISSUE TITLE
Evaluate whether we can solve the "duplicate problem"

### ISSUE THREAD

**Issue by birkland** [eclipse-pass/main#149] opened 2021-04-13 13:57 UTC
Figure out if there are any architectural changes that should be made in order to better deal with data integrity problems related to duplicate resources.

Duplicate resources (Users, Funders, Grants, for the most part) have been a major pain point for PASS over the past couple years.  Certain "primary keys" are expected to be unique across the entire repository, but it is up to individual services and applications to enforce uniqueness wherever it matters.  Firsthand experience has shown us on numerous occasions that this doesn't work in practice:  we constantly need to find duplicates and remediate PASS data whenever something goes wrong.

Architecturally, the crux of the problem is that Fedora (the source of truth) does not offer relevant forms of data integrity checks.  Applications are left on their own to enforce integrity constraints, but Fedora itself is not queriable.  Instead, applications need to query elasticsearch.  Elasticsearch is asynchronously updated, so applications have had to implement "coping mechanisms" such as maintaining an internal cache of recently created objects to consult before hitting the index.  This has been costly, and is insufficient to protect against two different applications attempting to add the "same object"   Furthermore, the message broker has "gone down" on numerous occasions, leaving the elasticsearch index out of date with Fedora, and leading to the creation of duplicates despite internal caching workarounds.

First, define the list of objects and relevant fields that currently need to be enforced as unique (e.g. `locatorIds` must be unique for `Users`)

It may be useful to compile a list of applications that need to enforce uniqueness, and how they approach doing it.  

Then, figure out if we can eliminate this class of problem once and for all.  Possible avenues include:
* Replacing Fedora with a relational database with proper UNIQUE and FOREIGN KEY constraints
* Adding some sort of referential integrity service to Fedora
* Making elasticsearch index updates synchronous with Fedora updates
* Architecturally, allowing duplicates and making them an OK and natural occurrence.
* Anything else?

**Comment by jrmartino** [comment] 2021-04-13 16:59
I think Hanh has compiled the list of objects and fields described above. In most cases, the match is for a specific field value (like localKey for Grant) - the case for User is a little fuzzier. locatorIds is a list, and applications should check for these in descending order of reliability. a search succeeds if any of these ids is found.

The current architecture relies on a lot of moving parts being in good shape for the index to reflect what is in Fedora. An integrity check would be a good idea, and upon failure, object creation attempts blocked until integrity is restored. 

Making duplicates ok ... i worry about a problem with the index going undetected for months (could this happen?) with automated applications blithely creating duplicate objects undetected. It seems that each duplicate might contain partial information for the abstract object, which would then need to be assembled each time it was addressed. Scaling would need to be thought out with this approach. (Kind of like hyphenated last names over several generations). 

I think we have the tooling to check for duplicates, and remove certain ones (like users) lacking incoming links,  which only have relevance with incoming links (the java client can find all incoming links for an object IIRC). A maintenance service with these capabilities running at reasonable intervals, together with an integrity check as suggested by Aaron, might go a long way to fixing this problem. 

I'd also suggest that there is an opportunity here for us to consider the larger issue of prompt problem detection, robust communication, and clear roles, responsibilities, protocols etc. so that any issues are small in scope and duration.

**Comment by birkland** [comment] 2021-04-15 18:36
@jrmartino So are you suggesting that the fundamental architecture is sound (it is the application's responsibility for avoiding duplicates, and the tool available for that is an async/eventually-consistent index), but the real pain comes from lack of monitoring and problem detection?

**Comment by jrmartino** [comment] 2021-04-15 19:39
@birkland That is my relatively uninformed suggestion.  Applications cannot really avoid duplicates if the cause is a broken index which returns an empty result instead of an error. But my feeling is that the best path might be to address (fix or mitigate)  the causes of  the issues with the current architecture, and see how much improvement we can gain. And yes, I think that we should never have to ask, "how long has this service been down?" - i'd rather the conversation start, "the service failed for the first time last night"

**Comment by birkland** [comment] 2021-04-16 13:19
@jrmartino So I am increasingly convinced that the current architecture guarantees that duplicates and other sorts of data inconsistencies will eventually occur.  I think certain aspects will need to be re-evaluated in the context of Eclipse.  For now though, I think the answer of whether we can solve "the duplicate problem" for real (in the short term) seems to be _no_; but we _can_ take some steps to make it less painful as low-hanging fuit.

Can you write up a proposal that enumerates the specific tooling, checks, and notifications that would be feasible to write in the short term, among with enough design details to give a good idea how exactly each tool would work, how costly it would be to implement, and ultimately help make a decision to green-light development on some of these tools?

**Comment by jrmartino** [comment] 2021-04-16 14:07
@birkland  I think we can look at periodic maintenance practices as well as some real-time remediation, at least in the case of java client interactions with Fedora. I'll be happy to think about it and write something up.

**Comment by markpatton** [comment] 2021-04-22 15:07
Suppose a PASS client is solely responsible for writing some types of PASS objects and wants to avoid duplicates and be reasonably fast. Define a hash function H(P) that returns the same value for all PASS objects considered equivalent. This does not preclude non-equivalent PASS objects from having the same hash value, but the function should be defined in such a way to make collisions unlikely. Define a function U(P) that maps a PASS object a Fedora object URI. The URI must depend only the PASS object type and H(P). (This could be done trivially by appending H(P)  and the PASS object type as path segments to the Fedora base URI.)

To write a PASS object P to Fedora, the client first computes U(P) and attempts to retrieve the Fedora object F with that URI.
If F does not exist, then P is not a duplicate object and is written to Fedora as U(P). This should be a common case.

If F does exist, then either P is a duplicate of an existing PASS object or there was a hash collision.
If P is a duplicate, nothing needs to be done.
If P is not a duplicate, then P is written to Fedora with a new random URI.

Unfortunately this duplicate check may require some work. A first quick step is to compare the PASS object corresponding to F with P. If they are equivalent, a duplicate has been found and the check is done. This should be the common case. If they are not duplicates, then Elasticsearch must be queried for duplicates. This last hopefully rare case happens when there are multiple collisions and will be slow.

**Comment by jrmartino** [comment] 2021-04-22 16:50
We currently leave to Fedora the task of assigning a URI for an object when it is created. It would be a lot easier if we could, as Mark suggests, instead have a way of computing a URI on the client side upon object creation.  For many objects there is a field which is unique and immutable (at least for a given Entity type).  If we could assign a URI on the client side when creating an object, we'd be in a good position.  Every client could use the same algorithm, so for example any Funder with localKey 123453 would resolve to the same computed URI value, with any client. I think this is what Mark is suggesting. I'd go for this in starting a PASS repo from scratch.

Unfortunately, we have many objects already in Fedora whose URIs are not computable on the client side, and we would have to store them somewhere. Maybe another "backup" index designed for the simple purpose of determining existence might help us. 

implementing Mark's idea fully might require a data migration changing all existing URIs to our custom computed URIs. It would be a little trickier for Users, which have a fuzzier scheme for locatorIds, since not all of these are immutable. We might not be able to have every client resolve Users, since different locator IDs are available. We may be able to rectify this with directory lookup services (HopkinsID <-> JHU EmployeeID) as we do in the COEUS data pull.

**Comment by markpatton** [comment] 2021-04-22 17:59
@jrmartino Using known unique identifiers is nice and would work well if you can. This suggesting is basically faking that with a hash and then dealing with the hopefully rare case of hash collisions. You are right that this is probably impractical right now because it would require starting from scratch with an empty repo and then writing in the new objects using this method. Note that this method does not handle multiple pass clients creating the same object type.

**Comment by jrmartino** [comment] 2021-04-26 20:50
some thoughts on this are here: https://docs.google.com/document/d/1Uv-29J4B3pMQrieYgOULTZMPvyAylbHOJwRC4ZEupi8/edit?usp=sharing

**Comment by jrmartino** [comment] 2022-04-28 19:27
See continuation with a specific proposal for remediation #212

**Closed by jrmartino** 2022-04-28 19:27 UTC
