### ISSUE TITLE
Pass UI error when initializing new submission with grant

### ISSUE THREAD

**Issue by jabrah** [eclipse-pass/main#607] opened 2023-06-16 18:52 UTC
When starting a new submission from the grants page with the intent on automatically adding the selected grant to the new submission, I am getting an Ember error when transitioning between steps 1 and 2 (basics to grants selection)

```
Error occurred:

- While rendering:
  -top-level
    application
      submissions
        submissions.new
          submissions.new.grants
            workflow-wrapper
              workflow-grants

Handling error: "Assertion Failed: You attempted to update `ref` on `Tag`, but it had already been used previously in the same 
computation.  Attempting to update a value after using it in a computation can cause logical errors, infinite revalidation bugs, and 
performance issues, and is not supported.\n\n`ref` was first used:\n\n- While rendering:\n  -top-level\n    application\n      
submissions\n        submissions.new\n          submissions.new.grants\n            workflow-wrapper\n              
workflow-grants\n\nStack trace for the update:"
```

![image](https://github.com/eclipse-pass/main/assets/5167587/fb475477-4d0e-4cda-a261-5504e32d5799)

**Comment by dkriethof** [comment] 2023-08-29 18:16
dupe of #696

**Closed by dkriethof** 2023-08-29 18:16 UTC
Labels: UI
